PRX/Infrastructure

bootstrap.yml, castle.prx.org/castle-proxy.yml, castle.prx.org/castle.prx.org.yml, castle.prx.org/pipeline.yml, root.yml
Add pipelines for (new) castle.prx.tech.
=> Init Castle

codebuild/README.md, codebuild/bootstrap.sh, codebuild/scripts/bootstrap.sh
Script to run tests and push-to-ECR any PRX app.
See the README in the codebuild directory for usage.
=> Codebuild bootstrap script

stacks/audiogram.yml, stacks/castle.prx.org.yml, stacks/cms.prx.org.yml, stacks/ecs.yml, stacks/publish.prx.org.yml, stacks/root.yml, stacks/upload.prx.org.yml
=> Castle secrets

stacks/publish.prx.org.yml, stacks/root.yml
Update publish to:
Requires PRX/publish.prx.org#401 to make Publish use aws-secrets.
=> Update publish configs

stacks/play.prx.org.yaml, stacks/root.yml
Don't merge until after play PR is merged
=> Add boilerplate for Play stack

secrets/lambdas/secrets-s3-update/lambda_function.py
lambda not happy with this print syntax, add parenthesis
=> fix print statement

stacks/root.yml, stacks/web-application.yml
* Added param for app name to use throught template
* Added container related params for cpu, mem, port
* Added a conditional param for making worker resources or not
=> Web template for apps with worker or not

stacks/ecs.yml
=> More launch config

stacks/dovetail.prx.org.yml, stacks/load-balancers.yml, stacks/root.yml, stacks/web-alb-application.yml
Give feeder an ALB.  Mostly copied out of dovetail and the other shared stack.
=> Shared ECS + ALB stack for feeder

stacks/root.yml
See #68.
PRX/id.prx.org#36 has to get merged first.
=> Add ID service

stacks/metrics.prx.org.yml, stacks/root.yml
=> adds metrics

stacks/castle.prx.org.yml, stacks/dovetail.prx.org.yml, stacks/fourohfour.prx.org.yml, stacks/jingle.prx.org.yml, stacks/metrics.prx.org.yml, stacks/play.prx.org.yml, stacks/publish.prx.org.yml, stacks/root.yml
=> Normalize and update cpu/memory reservations

stacks/dovetail.prx.org.yml
First shot at autoscaling the dovetail service.
=> Dovetail service autoscaling

README.md, cd/lambdas/production-config-pseudo-source/lambda_function.py
=> Roll over S3ObjectVersion values from stag to prod config

stacks/analytics-ingest-lambda.yml, stacks/root.yml
Standardize alarm names, and add an invocations < 1500 alarm.
=> Lambda alarm names

stacks/ecs.yml, utility/lambdas/ecs-ami-lookup/index.js
Allows upgrading staging separately from prod.
=> Explicit ECS AMI names

stacks/analytics-ingest-lambda.yml, stacks/dovetail-stitch-lambda.yml, stacks/root.yml
Requires merge of PRX/dovetail-stitch-lambda#2
=> Dovetail stitch lambda

cloudfront/dovetail-cdn.yml
@cavis feel free to mess with the numbers
=> Add 5xx error alarm to DT CDN

stacks/upload.prx.org.yml
I added the minimum amount I thought I could get away with. Not sure how to test this at all.
=> Add CORS headers to GET response

cdn/dovetail-cdn.yml, cloudfront/dovetail-cdn.yml
Set explicit TTLs on 4xx / 5xx responses.
=> Custom error TTLs

stacks/dovetail-stitch-lambda.yml
Allow the stitch lambda to invoke an edge lambda of the same name.
For PRX/dovetail-stitch-lambda#10
=> Edge lambda invoke

stacks/proxy.prx.org.yml, stacks/root.yml
First shot at deploying a dummy api.
=> Proxy lambda/api

cdn/s3-origin.yml
Template for S3 origin CDNs, including a single-page-app setting which redirects 403s to your index.html.
=> S3 origin CDN

utility/lambdas/s3-static-site-deploy/lambda_function.py
Expire HTML sooner in CloudFront.
=> Max-age for html

dns/prx.mx-hosted_zone.yml
consolidating down to one heroku app, moving prx.mx to point to it
=> Use just one heroku app, choosing remix-select as it owns the db

dns/prx.org-hosted_zone.yml
=> Move allusionist cdn

stacks/proxy.prx.org.yml, stacks/root.yml
Have proxy just create its own certs.  And make sure those work for `https://prx.org` ... so it can redirect that to www.
=> Proxy certs

dns/prx.org-hosted_zone.yml, stacks/proxy.prx.org.yml
=> Move www to proxy

cdn/dovetail-cdn.yml, stacks/dovetail-stitch-lambda-alarms.yml, stacks/dovetail-stitch-lambda.yml
See PRX/dovetail-stitch-lambda#6.
=> Stitch lambda alarms

README.md, cd/cd.yaml
=> Add support for CloudWatch Event CodePipeline trigger

db/mysql-instance.yml, db/rds-policy-override.json
and names the DBInstance. adds policy override file for use during restore from snapshot
=> adds CloudWatch Alarms

db/elasticache.yml, db/mysql-instance.yml, db/vpc.yml
=> Stack to make an elasticache memcached cluster

stacks/legacy-support/root.yml, stacks/legacy-support/stripe-proxy.yml, stacks/root.yml, stacks/stripe-proxy.yml
=> Add stripe proxy

ci/utility/post_build.sh
=> Create ECR repository when necessary

stacks/root.yml, stacks/vpc.yml
Allows the role the be assumed by anyone in the organization
=> Add assumable role for VPC peering

dns/prxu.org-hosted_zone.yml, stacks/dovetail.prx.org.yml, stacks/root.yml
=> Remove dovetail nginx

dns/prx.org-hosted_zone.yml
DNS change to move cms.prx.org
=> Move cms to aws

ci/lambdas/codebuild-callback-handler/lambda_function.py
=> Improve CodeBuild callback handling

stacks/container-apps/root.yml
Overkill, to prep for moving off contegix.
=> More exchanges

stacks/root.yml, stacks/serverless/dovetail-counts-lambda.yml, stacks/serverless/root.yml, stacks/vpc.yml
Requires PRX/dovetail-counts-lambda#3 first.  I'm not completely confident all of these things will work!
=> Dovetail counts lambda

dns/prx.org-hosted_zone.yml
=> Move exchange to ECS

stacks/container-apps/exchange-say-when.yml, stacks/container-apps/root.yml
Can only run 1 SAY_WHEN_THREAD worker for exchange
=> Single threaded Exchange say_when

stacks/load-balancers.yml
Fairly sure that syntax is correct
=> Bump the ALB idle timeout

stacks/container-apps/root.yml, stacks/root.yml
Dont merge this until courier is ready to roll out.
This sets up a new stack for the courier app (based on how cms works).
=> new courier stack

db/postgresql-instance.yml
Based on a pared-down version of the MySQL template, this PR adds a new CFN template that creates RDS PostgreSQL resources.
Per:
https://github.com/PRX/courier.prx.org/issues/8
https://github.com/PRX/augury.prx.org/issues/1
=> Create a new postgresql template

stacks/container-apps/root.yml, stacks/root.yml
Don't merge this until augury is ready to roll out.
This sets up a new stack for the augury app (based on how courier works).
=> Augury stack

etc/elasticsearch.yml
Creates a simply Elasticsearch Service deployment template, with limited customization
=> Add basic Elasticsearch Service template

stacks/container-apps/root.yml, stacks/container-apps/scheduled-task.yml, stacks/container-apps/scheduled-worker.yml, stacks/container-apps/web-application.yml, stacks/root.yml
Create a template for adding CloudWatch event scheduled triggers for tasks
Have the web-application.yml export task definitions to schedule
Add the remix application
Add a scheduled task for remix with hourly command to `load_episodes`
=> Add remix application with scheduled task

db/castle-postgres-instance.yml
RDS template for Castle postgres 11.  Setup and working in Staging and Prod data accounts.
=> RDS castle postgres

security/waf-sample.yml
This was really only to get familiar with the system and have a basic reference
=> WAF sample template

dns/prx.org-hosted_zone.yml, stacks/container-apps/root.yml
=> Enable augury prod

buildspec.yml, stacks/dovetail-stitch-lambda.yml
Should merge concurrently with PRX/dovetail-stitch-lambda#51
=> Stitch lambda to node 10

stacks/container-apps/root.yml, stacks/container-apps/sphinx-nlb.yml, stacks/root.yml
I think I have everything I need? not entirely sure, and the `Protocol: TLS` isn't validating locally in cfn-lint even though the docs say that is supported for https endpoints.
Anyway, pls have a look.
=> Add sphinx service and Network Load Balancer

stacks/serverless/dovetail-countemporary-lambda.yml, stacks/serverless/root.yml
Create a dup dovetail-counts-lambda with _no kinesis trigger_.  (That last part is important)
=> Temporary duplicate counts lambda

buildspec.yml, ci/ci.yml, notifications/lambdas/cloudwatch-alarm-notification-handler/lambda_function.py
=> Catch CloudWatch Alarm handler errors

stacks/serverless/dovetail-counts-lambda.yml, stacks/serverless/root.yml
=> Dovetail Counts Lambda alarms

stacks/dovetail.prx.org.yml, stacks/root.yml
Setup [dovetail-elixir](https://github.com/PRX/dovetail-elixir) app under the Dovetail ALB.
Will need to merge PRX/dovetail-elixir#7 first.
=> Dovetail elixir

dns/prxu.org-hosted_zone.yml
Adds DNS for dovetail-router app:
```
dovetail-router.prxu.org
dovetail-router.staging.prxu.org
```
=> DNS records for dovetail-router

notifications/notifications.yml
=> Add email subscription to fatal SNS topic

cdn/dovetail-cdn/dovetail-stitch-lambda-filters.yml, stacks/castle.prx.org.yml, stacks/dovetail.prx.org.yml, stacks/load-balancers.yml
=> Tune alarms

db/postgresql-instance.yml
Revamp the shared postgres template a bit (which ~i don't _think_ was~ was not in use for anything yet).
I'm using this to create new "shared" postgres databases in the data accounts, and port things over from legacy.
=> Updated postgres template

dns/prx.org-hosted_zone.yml, stacks/proxy.prx.org.yml
All necessary DNS records should exist already when this merges and deploys
=> Use DNS validation for proxy.prx.org certificate

db/dynamodb-table.yml
This will need auto scaling alarms before it's ready for production
=> Add support for billing mode selection in DynamoDB template

utility/lambdas/ecs-asg-sizer/lambda_function.py
For PRX/internal#521
We've had issues where existing ECS cluster instances go bad.  Their ecs-agent disconnects, but we were still counting them towards the auto scaling CPU/Memory available.
This filters them out of the list of "free space" in the cluster.  Which also proactively terminates them down on line 179 of this script:
```python
launch = desc['Reservations'][0]['Instances'][0]['LaunchTime']
elapsed = datetime.datetime.now(datetime.timezone.utc) - launch
if elapsed.total_seconds() > ECS_AGENT_WAIT:
if not dry_run:
ec2_client.terminate_instances(InstanceIds=[iid])
return [f'terminating {iid} with stale ECS agent', True]
else:
return ['waiting for ECS agent connection', False]
```
Basically, if an EC2 server has been alive for more than `ECS_AGENT_WAIT` (600 seconds) and ecs-agent …
=> Terminate EC2 instances with disconnected agents

cdn/single-origin.yml
=> Parameterize CloudFront compression in single-origin

stacks/container-apps/augury-forecast.yml, stacks/container-apps/root.yml
Start building out the SNS relay to trigger augury forecast runs in fargate.
(Function code TBD)
=> SNS relay for Augury fargate

stacks/serverless/analytics-ingest-lambdas.yml
Permissions/ENV for PRX/analytics-ingest-lambda#65.
=> Analytics DDB Retries

cdn/single-origin.yml
=> Add header forwarding support to single-origin template

stacks/dovetail-stitch-lambda.yml, stacks/root.yml
Related to PRX/dovetail-stitch-lambda#54.  Should be merged before PRX/dovetail-stitch-lambda#57.
=> Permissions to call out to Porter

stacks/container-apps/root.yml, stacks/container-apps/web-application.yml, stacks/root.yml
=> Add iframely app stack

db/solr-ec2.yml, etc/serverless-s3-upload/lambdas/StaticWebsiteFunction/index.html, etc/simple-ec2.yml
=> Add Solr template

db/mysql-instance.yml
Added in newer m5 instance sizes.
=> Add m5 instance sizes, lint Cfn template

stacks/container-apps/augury-alarms.yml, stacks/container-apps/root.yml, stacks/container-apps/web-application.yml
Solves https://github.com/PRX/augury.prx.org/issues/156
Set up a metric and alarm for the augury workers to watch the invocations of workers pulling in actuals.
=> Set up a metric and alarm for augury

stacks/container-apps/root.yml
Time to try deploying networks to prod!
This gets rid of the IsStaging conditionals, I think that's all that needs to be done?
(secrets are already setup and deployed)
=> Enable prod networks and sphinx

dns/prx.org-hosted_zone.yml
Closes https://github.com/PRX/internal/issues/601
=> Remove old prx.org records

stacks/container-apps/web-application.yml, stacks/dovetail.prx.org.yml
Attempting to add a IAM role that only applies to the Courier web worker. I'm not intending this to every be done this way for a real app in production, just need to have something deployed to start checking behavior.
=> ECS task IAM role testing

db/mysql-instance.yml
added from here:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.VersionMgmt
=> Select Mysql EngineVersion from most recent supported versions

stacks/container-apps/root.yml, stacks/root.yml
Needed for https://github.com/PRX/iframely/issues/6
This shouldn't get merged until the secrets files have been created
=> Add aws-secret support for iframely stack

etc/sample-step-functions.yml, stacks/proxy.prx.org.yml, stacks/serverless/pixel.prx.org.yml
Updates the Lambda Node version used for the proxy app and pixel tracker
=> Update some node Lambdas

stacks/play.prx.org.yml
- Enable IPv6
- Switch to cache/request policies
- Enable brotli compression
- Remove unnecessary comments
=> Modernize the play.prx.org CloudFront resources

dns/prx.org-hosted_zone.yml
CNAME for support.prx.org to vanity.classy.org
=> Classy CNAME for support.prx.org

stacks/play.prx.org.yml
If I did everything correctly, the staging CDN is not in use anymore
=> Only create CDN for Play in production

.prettierrc.yml, stacks/root.yml, stacks/serverless/dovetail-cdn-arranger.yml, stacks/serverless/root.yml
Init the dovetail-cdn-arranger deployment.
=> Dovetail cdn arranger lambda

cdn/dovetail3-cdn.yml
Starting on a very basic Dovetail 3 CDN setup.  Marked some TODOs to fill in later.
=> Dovetail 3 CDN

stacks/root.yml, stacks/serverless/dovetail-cdn-arranger.yml, stacks/serverless/dovetail-cdn-origin-request.yml, stacks/serverless/root.yml
Initial setup for the to-be-edge-lambda'd "Dovetail CDN Origin Request".
=> CDN origin request lambda

db/dynamodb-table.yml
For PRX/analytics-ingest-lambda#75
=> Alarm on UpdateItem throttling

stacks/apps/augury.yml, stacks/container-apps/augury.prx.org.yml
Related to https://github.com/PRX/augury.prx.org/issues/545. Sets up some iam users to access the ad-files bucket and patches them into the augury environment.
=> Set up new IAM user and access keys

stacks/serverless/analytics-ingest-filters.yml, stacks/serverless/analytics-ingest-lambdas.yml, stacks/serverless/root.yml
Part of PRX/analytics-ingest-lambda#76.
Deploy before PRX/analytics-ingest-lambda#77.
=> Analytics ddb subscription filter

stacks/apps/augury.yml, stacks/container-apps/augury.prx.org.yml
Adding a few more static env vars related to: https://github.com/PRX/augury.prx.org/pull/574
=> Need a few more uploader related static vars

stacks/container-apps/augury-forecast.yml, stacks/container-apps/augury.prx.org.yml, stacks/container-apps/root.yml, stacks/root.yml
DO NOT MERGE YET.
Changes for PRX/internal#715 - use Aurora host + port 3306.
=> Legacy Augury staging to Aurora

stacks/apps/feeder.yml, stacks/container-apps/feeder.prx.org.yml, stacks/root.yml
DO NOT MERGE YET.
For PRX/internal#715
=> Staging feeder on aurora

stacks/apps/remix.yml, stacks/container-apps/remix.yml, stacks/container-apps/root.yml
DO NOT MERGE YET.
For PRX/internal#715.
=> Staging remix on aurora

stacks/vpc.yml
=> STS endpoint for VPC

stacks/root.yml
This is based on recently observed data
=> Reprioritize ALB listener rules

stacks/apps-300A.yml, stacks/apps/dovetail-legacy.yml, stacks/apps/dovetail-router.yml, stacks/apps/styleguide.yml, stacks/root.yml
Addresses issues identified in PRX/dovetail-router.prx.org#118 and PRX/dovetail.prx.org#380
=> Fixup new dovetail app templates

cdn/log-shipper.yml
Anonymize and ship dovetail3-cdn logs.  For PRX/internal#713.
=> Ship Dovetail3 CDN logs

stacks/apps/cms.yml, stacks/apps/exchange.yml, stacks/apps/id.yml, stacks/container-apps/cms.prx.org.yml, stacks/container-apps/exchange.prx.org.yml, stacks/container-apps/id.prx.org.yml, stacks/container-apps/root.yml, stacks/root.yml
For PRX/internal#723.
May need to add some params to the zipfile first.
=> Staging mysql aurora

stacks/apps-200A.yml, stacks/apps/remix.yml, stacks/container-apps/remix.yml, stacks/container-apps/root.yml
🚧  DO NOT MERGE until ready to move the DB.
Use Aurora for all Remix DBs, all the time.
=> Remix to Aurora

stacks/apps-200A.yml, stacks/apps/augury.yml, stacks/container-apps/augury-forecast.yml, stacks/container-apps/augury.prx.org.yml, stacks/container-apps/root.yml
🚧  DO NOT MERGE until ready to move the DB.
Use Aurora for all Augury DBs, all the time.
=> Augury to Aurora

stacks/apps/cms.yml, stacks/container-apps/cms.prx.org.yml
=> Explicit cms queues

stacks/apps-100A.yml, stacks/apps/cms.yml, stacks/root.yml
Refactors the policies from IAM user `prx.org-backend` into the ECS task role.
=> Refactor CMS IAM access into task role

db/shared-apps-aurora-pg/database-cluster.yml
Sets up performance insights in couldwatch for shared postgres
=> Enable performance insights

stacks/root.yml, stacks/shared-memcached.yml
Init a new memcached cluster - with larger prod instance type.
=> More memcached

stacks/jump-server.yml, stacks/root.yml
Builds a jump EC2 server, to access all sorts of VPC resources.  (And it'll be running some other temporary cron code, at least for now).
Some manual setup will still be needed - thus the deletion protection.  If it starts doing more things (handling awssh requests, etc) will formalize that setup.
=> Jump server

dns/prxu.org-hosted_zone.yml, stacks/apps-200A.yml, stacks/apps/feeder.yml, stacks/root.yml
=> Private feed proxy

stacks/apps-400A.yml, stacks/apps/the-castle.yml, stacks/dashboards.yml, stacks/root.yml
Added to `the-castle.yml` the def for a worker task that can run hourly.
Moved the EFS volume from the web service to the worker which needs it.
Updated parent stacks for additional param, and for having real ecr and secrets values for the new app stack
=> TheCastle worker

stacks/apps/augury.yml
Related to: https://github.com/PRX/augury.prx.org/pull/869/files
=> Add a 60 second lock timeout to the augury webs connection

stacks/root.yml
I think I configured that right, and that this will be the right place to also change over prod when we move from castle.prx.org to thecastle.prx.org
=> Configure staging to use new thecastle deployment

devops/aws-management/devops-iam-key-monitor.yml
=> Ignore deprecated chef user

stacks/root.yml, stacks/shared-ecs/asg.yml
No need to run 7 fairly hefty EC2 instances when there are no ECS tasks in us-west-2.
=> Save some dollars

stacks/apps-500A-tmp.yml, stacks/root.yml
=> Temporary multiregion dovetail stack

stacks/apps-100A.yml, stacks/apps-500A-tmp.yml, stacks/apps/dovetail-cdn-arranger.yml, stacks/root.yml
Moved the ffmpeg lambda layer to 2 places:
```
s3://prx-infrastructure-us-east-1-support/lambda-layers/ffmpeg-4.3.1.zip
s3://prx-infrastructure-us-west-2-support/lambda-layers/ffmpeg-4.3.1.zip
```
=> Multi region lambda-layer buckets

stacks/apps/the-castle.yml
Maybe I did the permissions right?
=> Add access to s3 bucket for writing logs

stacks/shared-ecs/asg.yml
This creates the key pair, but does not use it anywhere yet
=> Add EC2 key pair

dns/prx.org-hosted_zone.yml
Just a bunch of defunct `prx.org` subdomains
=> Remove legacy DNS records

dns/prx.org-hosted_zone.yml
=> Remove subdomains where the s3 bucket does not exist

stacks/jump-server.yml
Switch from elastic IP to an EC2 generated public IP.  (Elastic IP seems unnecessary?)
And use an ALIAS record rather than CNAME for the v4 IP address.
=> Fix jump server DNS

stacks/apps-100A.yml, stacks/apps-200A.yml, stacks/apps-300A.yml, stacks/apps-400A.yml, stacks/apps-500A-tmp.yml, stacks/apps/augury.yml, stacks/apps/castle.yml, stacks/apps/cms.yml, stacks/apps/dovetail-router.yml, stacks/apps/exchange.yml, stacks/apps/feeder.yml, stacks/apps/id.yml, stacks/apps/iframely.yml, stacks/apps/metrics.yml, stacks/apps/networks.yml, stacks/apps/play.yml, stacks/apps/publish.yml, stacks/apps/remix.yml, stacks/apps/styleguide.yml, stacks/apps/the-castle.yml, stacks/root.yml
Removes:
- stack parameters
- IAM policies
- environment variables
=> Remove aws-secrets remnants

stacks/apps-300A.yml, stacks/apps/dovetail-analytics.yml
Turn off the redis lambda, and configure the pingback-actuals ENVs in staging only.
=> Switch staging from redis increments to POSTs

stacks/apps-400A.yml, stacks/apps/exchange.yml, stacks/apps/wfmt.yml, stacks/dashboards.yml, stacks/root.yml
- Adds a taskuser b/c the app needs AWS API keys
- Adds an SES user to be able to do email
- Uses shoryuken worker, so needs a queue for that
- Works with Porter, so that is configured
- Created the postgres dbs for stag and prod, add credentials to SSM
- Added in the SSM values for other secret values
=> Add WFMT as an ECS service

stacks/apps-100A.yml, stacks/apps/id.yml
Make S3 GET request signing work
=> Give ID write access to mediajoint S3

stacks/apps-100A.yml, stacks/apps/dovetail-cdn-arranger.yml, stacks/constants.yml, stacks/root.yml
Blocked by https://github.com/PRX/dovetail-cdn-arranger/pull/22
=> Switch FFmpeg layer to published S3 object

cdn/publicfeeds-cdn.yml
Closes https://github.com/PRX/internal/issues/872
=> Add publicfeeds.net CDN template

stacks/apps-300A.yml, stacks/apps/augury.yml, stacks/root.yml
Sets up a redis instance for Augury, and passes the host/port to it.  (Though Augury won't start using redis without a code change).
=> Augury + Redis

dns/prx.org-hosted_zone.yml
=> Zoom domain name verification

dns/theworld.org-hosted-zone.yml
Here's the language directly from Microsoft, I copied it directly I think but def need a second set of eyes on it!
; Zone file for Microsoft 365 services - please append the data below to your zone file @ 3600 IN MX 0 theworld-org.mail.protection.outlook.com. autodiscover 3600 IN CNAME autodiscover.outlook.com. @ 3600 IN TXT "v=spf1 include:spf.protection.outlook.com -all"
=> MX, CNAME, and TXT record updates for theworld.org

stacks/apps-100A.yml, stacks/apps/id.yml
Adds key references for the new turnstile keys in Parameter Store. related to [ID #236: captcha to turnstile](https://github.com/PRX/id.prx.org/issues/236)
=> Add key refs for turnstile Parameter Store keys

stacks/apps/dovetail-analytics.yml, stacks/apps/dovetail-counts.yml
Closes PRX/internal#873.
Manually trying this in us-west-2 first.
=> Split kinesis batch on error

stacks/apps/dovetail-apple-api-bridge.yml
Fixes the invoke permissions to match what api gateway provided.
=> Set up permissions to match api gateway

stacks/apps/augury.yml
=> Set up alarms on error log level messages

stacks/apps/dovetail-metrics-export.yml
=> Add new TED shows

dns/prxu.org-hosted_zone.yml
Adds CloudFront aliases and certificate validation cname for `f.development.prxu.org`.
=> Development feeder

stacks/apps-200A.yml, stacks/apps/feeder.yml
Copied from the Publish stack.
=> Init feeder uploads bucket

stacks/apps/remix.yml
related to https://github.com/PRX/remix-select/pull/74
=> Add in channel id for slack notifications

stacks/apps/exchange.yml
Like the same thing for remix, but exchange!
(maybe they should share a value?)
=> Add default slack channel for exchange notifications

stacks/apps/id.yml
I think this should be deployed to staging today late in the day, and we'll hold the prod deploy until 9 AM ET tomorrow
=> Update mandatory SSO domains

spire/templates/constants.yml, spire/templates/shared-dovetail-kinesis.yml
Merge once we feel good about things from the manual switchover
Closes https://github.com/PRX/internal/issues/1001
=> Update Dovetail CDN hostname

spire/templates/root.yml, spire/templates/shared-alb.yml
Closes https://github.com/PRX/internal/issues/436
Gives us change-password support for all apps without having to build it in to each one.
=> Support change-password as ALB rule

spire/templates/apps/dovetail-metrics-export.yml
Requires https://github.com/PRX/dovetail-metrics-export/pull/13
=> Simpler path/file format for boostr exports

etc/cdn-log-shipper/cdn-log-reprocess.rb
seems like this is worth adding more officially - entirely possible we'll need it again!
=> ryan's script to reprocess cdn logs

spire/templates/apps/dovetail-cdn-arranger.yml
For https://github.com/PRX/dovetail-cdn-arranger/pull/33
=> Expire incomplete concats sooner

spire/templates/apps-400A.yml, spire/templates/apps/dovetail-cdn-usage.yml
Still needs some config.  But need the lambda there to test BigQuery access.
=> Init dovetail-cdn-usage lambda

spire/templates/shared-ecs/asg.yml
Closes https://github.com/PRX/internal/issues/1105
=> Use AL2023 for ECS in prod

spire/templates/apps-200A.yml, spire/templates/apps/publish.yml
Redirect publish -> feeder, and change task count to 0 for now.
=> Redirect publish

spire/templates/apps/dovetail-cdn-arranger.yml, spire/templates/shared-clickhouse.yml
Adds some metrics, so we can figure out the breakdown between file types.
=> CDN arranger bucket metrics

etc/pgdump-to-s3/template.yml
Exclude the binary augury_blobs table from backups
=> Exclude the augury_blobs table

spire/templates/apps-300A.yml, spire/templates/apps/augury.yml, spire/templates/root.yml, spire/templates/shared-clickhouse.yml
Based on https://github.com/PRX/Infrastructure/pull/771
=> Patch through parameters for augury clickhouse

spire/templates/apps/dovetail-analytics.yml
wrong stream, need the output of the counts, not the input
=> Fix which stream of events we use for freq cap counting

dns/prx.org-hosted_zone.yml
You can create an account and use your domain as your handle, if you verify using DNS:
https://bsky.social/about/blog/4-28-2023-domain-handle-tutorial
=> Bluesky app domain verification

spire/templates/shared-ecs/asg.yml
Closes https://github.com/PRX/internal/issues/1180
Closes https://github.com/PRX/internal/issues/1105
=> Use AL2023 for Spire prod ECS instances

spire/templates/root.yml, spire/templates/shared-redis/cluster.yml
Back to medium instances in us-west-2 prod.
=> Revert "Use cache.m6g.large everywhere"

spire/templates/apps-200A.yml, spire/templates/apps/augury.yml, spire/templates/apps/exchange.yml, spire/templates/apps/feeder.yml, spire/templates/apps/id.yml, spire/templates/root.yml
TODO: remove 2 parameterstores:
```
/prx/global/Spire/honeycomb-api-key
/prx/global/Spire/signoz-access-token
```
=> Remove signoz ENVs

spire/templates/apps-300A.yml, spire/templates/apps/dovetail-router.yml, spire/templates/root.yml, spire/templates/shared-ecs/asg-aarch64.yml
Deploy with https://github.com/PRX/dovetail-router.prx.org/pull/352
=> Update Dovetail Router service for aarch64

spire/templates/apps/augury.yml, spire/templates/apps/dovetail-router.yml, spire/templates/apps/exchange.yml
Bring more critical services in line with forthcoming defaults
=> Enable AvailabilityZoneRebalancing

spire/templates/apps-400A.yml, spire/templates/apps/dovetail-spots.yml, spire/templates/dashboards.yml, spire/templates/root.yml
Working on a deploy of Spots.
Note to self: set param store stuff and create the db before merging.
=> Spots deploy

dns/theworld.org-hosted-zone.yml
https://help.opensense.com/docs/dns-entries-must-have?highlight=DNS
=> Add in Opensense for theworld.org

spire/templates/apps-400A.yml, spire/templates/apps/dovetail-spots.yml, spire/templates/constants.yml, spire/templates/root.yml
=> Init worker and log alarms

spire/templates/dovetail-redis/cluster.yml, spire/templates/dovetail-redis/security-groups.yml, spire/templates/root.yml, spire/templates/shared-app-redis.yml
Just to prevent confusion. CFN will consider this a no op
=> Rename Dovetail Redis directory
