- codebuild/README.md
- codebuild/bootstrap.sh
- Add `PRX_GITHUB_PR` env
- Add `prxGithubPr` to SNS json
- Ignore `PRX_ECR_TAG` if no Dockerfile is present
- Rename `SNS_CALLBACK` -> `PRX_SNS_CALLBACK`, to be more consistent.  (All custom inputs namespaced to PRX_).
> More params

- ci/lambdas/github-event-handler/index.js
Also pass the branch name to CI codebuild, so our [codecov fork](https://github.com/PRX/codecov-node) can work without the `.git` directory.
> Include branch name in CI

- stacks/root.yml
Adding feeder-web to Infrastructure. 
I believe that the feeder.prx.org repo is already set up for migration, so the next steps will be:
(More info on steps [here](https://github.com/PRX/prx.org/wiki/Migrating-backend-apps-to---PRX-CICD))
> add feeder-web to Infrastructure

- stacks/certificate.yml
- stacks/dovetail.prx.org.yml
- stacks/root.yml
Get dovetail running in ECS, with an independent load balancer from the rest of Platform.
Does **not** include the NGINX reverse proxy cache.  Will work on that after DT is running here.
Will also require most of #62 before we move prod over.  But this _should_ be able to run before that happens.
> Dovetail app stack

- stacks/dovetail.prx.org.yml
Init NGINX reverse proxy cache for Dovetail.  Which will hijack `/+/*` paths in the load balancer, and then rewrite those to `/=/*` under the VPC DNS name.
> Dovetail NGINX proxy

- cd/cd.yaml
- stacks/root.yml
For custom resources it can be useful to have a value that changes each
time the pipeline runs. This uses the S3 object key for an artifact
that is always created, and therefore should be unique to each pipeline
execution
> Add a mostly-random nonce to Root stack for utility purposes

- stacks/ecs.yml
- utility/lambdas/ecs-drain-tasks/lambda_function.py
Fixes #96.
Use a lifecycle hook to drain ECS tasks before an instance terminates.  Prevents ALB 500s while it's waiting for the health-check to fail.
See https://github.com/awslabs/ecs-cid-sample
> Drain ECS tasks before terminating

- cd/cd.yaml
- etc/README.md
- etc/prx.mx-hosted_zone.yml
- etc/prx.org-hosted_zone.yml
- etc/prxu.org-hosted_zone.yml
- etc/radiotopia.com-hosted_zone.yml
- etc/radiotopia.fm-hosted_zone.yml
Adds templates for Route 53 hosted zones for several domains that already exist in Route 53, as well as prx.org, which currently is hosted on Contegix's name servers.
> DNS record templates

- stacks/dovetail.prx.org.yml
Working towards #110.  Spin up another dovetail service/target-group, without the 1-per-instance constraint on it.
After this finishes, will change the target-group under the http/https listeners.  And watch for errors for awhile before tearing down the old service/target.
(This should enable a very quick rollback, if need be).
> Unconstrained dovetail

- notifications/lambdas/slack-message-relay/index.js
- notifications/notifications.yml
- stacks/ecs.yml
- stacks/root.yml
- utility/lambdas/ecs-asg-sizer/lambda_function.py
See #10.  Attempts to scale an auto-scaling-group to most effectively fit an ECS cluster.
The 3 "threshold" ENVs (cpu/memory/count) configure a theoretical task that you always want to leave room for on the cluster.  It should have reservations at least as big as the largest task running on your cluster.
For instance, if you set those to 700/1400/2, this lambda would make sure there was always room for 2 more tasks on the cluster, with 700 cpu and 1400 memory.  If not, it scales up by 1.
Scaling down is a bit more complex.  You can't know which instance/tasks the ASG will kill when scaling down, so just assume it's completely full of these big "threshold" tasks.  So if 1 instance can hold 4 threshold tasks ... and I need space for 2 more tasks so we don't immediately scale back up ... …
> ASG sizing lambda

- .gitignore
- stacks/ecs.yml
- utility/lambdas/ecs-asg-sizer/lambda_function.py
Seeing an issue where EC2 instances connect to the ASG (show up as healthy there), but the ecs-agent never connects.  So the sizer lambda was just spinning forever, waiting for that agent to connect.
This now looks at how long those instances have been up.  If more than 10 minutes passes without it connecting to ECS, it gets terminated.
> ECS connection timeout

- ci/ci.yml
Give codebuild access to aws-secrets.  (Assumes names of managed policies will stay the same).
> Codebuild secrets

- stacks/analytics-ingest-lambda.yml
- stacks/root.yml
Creates the 3 analytics lambdas, for bigquery/pingbacks/redis.
- Not sure the alarms are what we actually want
- Does not include any log metrics (tend to use these more than error counts in our monitoring)
- Does not include any actual secret ENVs
- Will try adding these manually, and check if CFN blows them away on subsequent deploys
- Does not include any triggers
- Don't actually want kinesis triggers in CFN, yet
> Analytics ingest lambdas

- ci/lambdas/github-event-handler2/index.js
Anything using codecov will also need to know which branch is being built.
> Include PRX_BRANCH in ci

- stacks/ecs.yml
- stacks/root.yml
These currently exist in CloudWatch Alarms but are managed manually.
This change moves them into code. They are currently considered
Dovetail alarms, so this changes them to be more generic, since they
are.
> Move ASG networks alarms to Cfn

- etc/prx.org-hosted_zone.yml
This is mostly to see what's broken if we just turn it on as is.
> Add exchange.prx.org A record

- cdn/dovetail-cdn.yml
- cdn/feeder-cdn.yml
Per PRX/dovetail-stitch-lambda#9 ... going to start returning 404s early.  And a 403 really means that the stitch-lambda uploaded a file, but the origin-pull couldn't access it (S3 eventual read consistency).
Also added the feeder `f.prxu.org` and `f-staging.prxu.org` CDNs into this PR.  Haven't switched the DNS from Highwinds yet, but they're in place when we're ready.
> Noisy origin-pull 403s

- dns/prx.org-hosted_zone.yml
Had to start and stop for AWS maintenance, the external IP changed, and so it is updated here.
> Update up address for experiments

- stacks/dovetail-stitch-lambda-alarms.yml
🚧WIP StackSet to deploy lambda log-metrics/alarms in all our edge regions.
> Dovetail stitch lambda logs/alarms

- stacks/proxy.prx.org.yml
- Move proxy from prx.tech -> prx.org (so oauth can hopefully work there)
- Create the www.prx.org custom domain, but not the route53 record (since exchange continues to own that right now)
> Move proxy to prx.org

- stacks/proxy.prx.org.yml
Currently, the staging proxy doesn't work because:
1. The cert doesn't work for `proxy.staging.prx.org` (changed to .tech)
2. Pointed at the wrong exchange
3. Looking for the wrong session cookie
> Fix staging proxy

- db/rds-mediajoint.yml
- stacks/rds-mediajoint.yml
intended to be run manually as follows:
`aws cloudformation update-stack --stack-name <stack name> --template-url <template url> --parameters ParameterKey=DBName,ParameterValue=mediajoint_production ParameterKey=DBUser,ParameterValue=<admin but not actually SUPER user> ParameterKey=DBPassword,ParameterValue=<admin user password> ParameterKey=DBAllocatedStorage,ParameterValue=<GB of storage> ParameterKey=DBInstanceClass,ParameterValue=<RDS tier> ParameterKey=EC2SecurityGroup,ParameterValue=<ssh tunnel security group id> ParameterKey=RDSSubnetGroup,ParameterValue=<Platform-Production subnet group name>`
> adds template for RDS mediajoint instance

- cdn/feeder-cdn.yml
Make sure CORS headers are always cached in cloudfront, by always setting an `Origin` when requesting files from S3.
> Cloudfront CORS headers

- stacks/castle.prx.org.yml
- stacks/dovetail.prx.org.yml
- stacks/ecs.yml
- stacks/jingle.prx.org.yml
- stacks/root.yml
- stacks/web-alb-application.yml
- stacks/web-application.yml
See PRX/dovetail.prx.org#259
Currently we run around 8 `m4.large` instances in prod.  This is less necessary now that DT stitching is _mostly_ done in lambdas.  This moves the cluster back to `t2.medium` and changes some of the memory reservations to accommodate more tasks per instance.
Will want to disable prod deploys while testing this out in staging.  To make sure the t2 unlimited stuff actually works.
> Downsize prod cluster

- stacks/proxy.prx.org.yml
See PRX/proxy.prx.org#13.
Note: the ApiGateway does normally return ~10 500s a day, which are actually coming from proxying to squarespace:
```
[INFO] Proxy 500 POST corporate.prx.tech/api/1/wp-rum/record
```
I guess this is expected behavior then?  Certainly don't want to get into the habit of retrying things for squarespace.  This alarm should _not_ trigger on those, since they're fairly spread out through the day.
Also looked at the ApiGateway `Latency` metric, but it didn't seem very useful.  Would not have caught any issues we've seen thus far.
> Add alarm for proxy 500s

- cdn/dovetail-cdn.yml
- stacks/analytics-ingest-lambda.yml
- stacks/castle.prx.org.yml
- stacks/dovetail-stitch-lambda-alarms.yml
- stacks/dovetail.prx.org.yml
- stacks/ecs.yml
- stacks/jingle.prx.org.yml
- stacks/legacy-support/root.yml
- stacks/legacy-support/stripe-proxy.yml
- stacks/load-balancers.yml
- stacks/metrics.prx.org.yml
- stacks/play.prx.org.yml
- stacks/proxy.prx.org.yml
- stacks/publish.prx.org.yml
- stacks/serverless/root.yml
- stacks/static-sites/root.yml
- stacks/upload.prx.org.yml
- stacks/web-alb-application.yml
- stacks/web-application.yml
This resolves a majority of the CloudFormation template linting errors. Base on my testing Cfn does not consider these type changes to be stack changes (ie it seems to be doing the coercion before determining if definitions have changed), so pretty much none of these should actually be resource updates. The only ones that I'm worried about in here are the `TimeoutInMinutes` on nested stacks. Again, I don't think it will do anything, but if for some reason it does register those as changes the docs says updating that value "isn't supported", so idk what that would do, hopefully not replace. Will just need to keep an eye on things in staging once this gets merged.
> Clean up template errors

- stacks/ecs.yml
At some point, the output of docker info changed, breaking the cron that reports cloudwatch metrics:
```
Data Space Available: 71.09 GB
Metadata Space Available: 77.54 MB
Data Space Available: 71.09GB
Metadata Space Available: 77.54MB
```
This sed re-inserts the space, if it's missing.
> Fix docker available space metric

- db/mysql-instance.yml
* MasterUsername/MasterUserPassword linting fix by creating a separate restored db instance resource
* cleans up type linting, quotes, and other non string types
* also adds DependsOn for the RDSSubnetGroup to finish creation before the database is created
> fix linting

- cdn/dovetail-cdn/dovetail-stitch-lambda-filters.yml
- stacks/dovetail-stitch-lambda.yml
> Stitch lambda updates

- secrets/README.md
- secrets/lambdas/secrets-s3-update/lambda_function.py
Enhancing `aws-secrets` to securely store files other than just `/app/env/secrets` (e.g. private key files). https://github.com/PRX/aws-secrets/pull/6
However, if they are stored in the same `/app/env/*` path, they are picked up as changes to the secrets.
This change causes the secrets update lambda to ignore changes to files that are not names `/secrets`
> Secrets lambda ignores files other than secrets

- dns/prx.org-hosted_zone.yml
`api.prx.org` has always gone to the exchange app, since it was hosted on contegix at the apex domain.
Need to specify this explicitly now to go to AWS via the `exchange.prx.tech` address.
> Add a CNAME from for api.prx.org to exchange tech hosted on aws

- etc/cms-resource-reporter.yml
- etc/resource-reporter.yml
This PR sets up a new lambda that monitors the CMS create SNS topic and posts details to slack.
> notify slack when new series are created

- cd/lambdas/pipeline-approval-notification-handler/lambda_function.py
This PR sets up a some release guidelines for pushing the deploy button in CD. A small set of instructions are prepended to the release button that appears in Slack when things are merged to master.
> prepend release notes to the release button

- cd/lambdas/pipeline-approval-notification-handler/lambda_function.py
- notifications/lambdas/ike-interactive-messages-callback-handler/index.js
- notifications/notifications.yml
Add an additional deployment approval button that will, in addition to approving a production deploy, open a dialog prompting for release notes, which will get posted to #tech-releases
This is not really tested
Closes #275
> Add release notes prompt to deploy approvals

- stacks/castle.prx.org.yml
- stacks/container-apps/web-application.yml
- stacks/metrics.prx.org.yml
- stacks/play.prx.org.yml
- stacks/publish.prx.org.yml
- stacks/web-alb-application.yml
For #287.
Change all target groups to have health check:
- frequency of 15 seconds
- timeout checks after 5 seconds
- healthy after 3 successes
- unhealthy after 3 failures
> Faster health checks

- cdn/dovetail-cdn/dovetail-stitch-lambda-filters.yml
2 new logged statements to handle from PRX/dovetail-stitch-lambda#46
```js
{"_logLevel":"warn","msg":"Stale arrangement the-digest","location":"https://dovetail.prxu.org/program_id/guid/anything.mp3","_tags":["log","warn"]}
{"_logLevel":"warn","msg":"Expired arrangement the-digest","location":"https://dovetail.prxu.org/program_id/guid/anything.mp3","_tags":["log","warn"]}
```
This creates a new metric to handle both.  Will have to be deployed manually via StackSet.
> Metric for lambda redirect

- stacks/analytics-ingest-lambda.yml
Changed our kinesis stream to have fewer shards (3).  And the new "combined" downloads+impressions kinesis records also increase the amount of work-per-record the lambdas have to do.
> Analytics lambdas updates

- stacks/analytics-ingest-lambda.yml
- stacks/root.yml
- stacks/serverless/analytics-ingest-alarms.yml
- stacks/serverless/analytics-ingest-lambdas.yml
- stacks/serverless/root.yml
Initialize the analytics-dynamodb-lambda.
Can confirm those parameterstore values with:
```
aws ssm get-parameters-by-path --path /prx/stag/analytics-ingest-lambda/
aws ssm get-parameters-by-path --path /prx/prod/analytics-ingest-lambda/
```
> analytics-dynamodb-lambda

- db/dynamodb-table.yml
Creates a dynamodb table.  Optionally:
- Sets an expiration/TTL field
- Creates a role to grant access to an account-id
- Grants access to a specific pre-existing role in that account (maybe will use this later)
> DynamoDB table template

- stacks/root.yml
- stacks/serverless/pixel.prx.org.yml
- stacks/serverless/root.yml
Initial deployment for a pixel tracker API gateway [pixel.prx.org](https://github.com/PRX/pixel.prx.org).
This goes the same route as proxy.prx.org, and just sends _all_ HTTP methods and paths on to the lambda.  May dial that back at some point, to reduce load.  But this seemed like an easy place to start.
> Pixel tracker

- stacks/container-apps/exchange-alarms.yml
- stacks/container-apps/root.yml
- stacks/container-apps/web-application.yml
For PRX/exchange.prx.org#508
- Adds fatal alarms for `Prx3ProductionDeliveryUpdate` and `Prx3ProductionSayWhen`
_(We actually already had some alarms, but they were ops-error, and the thresholds may have been a bit too lenient.  Will delete them after this deploys)_
- Adds autoscaling to the ECS Worker tasks, but not the say_when task, which I _think_ per PRX/exchange.prx.org#446 has to be a singleton.  (Running more than one would result in duplicate tasks getting scheduled)
The scaling rules I went with, using Prx3ProductionDeliveryUpdate ApproximateNumberOfMessagesVisible:
- If between 0 and 1 once in 1 minute, scale in by 2
- If between 1 and 10 once in 1 minute, scale in by 1
- If between 20 and 100 once in 1 minute, scale out by 2 (cooldown 2 minutes)
- If between 100 and 400 once …
> Exchange worker autoscaling

- stacks/container-apps/root.yml
- stacks/root.yml
Not sure we've ever removed a stack before. The parameters will have to be removed from the template config manually before it's deployable, even for production.
> Remove Jingle stack

- stacks/load-balancers.yml
Makes the default action for ALB listeners a fixed 404 response, rather than forwarding to the default target group. This is part of #350. If the results are as expected, the fourohfour service (and default TG) can be removed.
> Replace default ALB action

- stacks/container-apps/sphinx-nlb.yml
I think this will correctly setup 2 target groups on one NLB, each with their own port, and then map an ECS service to connect to both.
> Configure NLB to have 2 target groups, and the ecs service to use both

- stacks/root.yml
Reorder the rules to optimize for current traffic patterns. Closes #359
It should avoid using any existing rule prefixes, even ones that are being unassigned.
> Reprioritize ALB listener rules

- cdn/single-origin.yml
Adds some additional conditions to handle cases where no preexisting ACM cert ARN is provided and no CNAMEs are provided. Previously it would fail because it would try to mint a cert, which it couldn't do without at least one CNAME. I guess this was more of a `fix/` than a `feat/`
> Allow single-origin CDNs without certificates

- etc/commitchange-ses.yml
- etc/sample-step-functions.yml
- stacks/dovetail.prx.org.yml
- stacks/root.yml
Sets up a subscription to the dovetail router log -- pushing those logs onto the bytes kinesis stream . Eventually, these dt-router impressions will be ingested by the bytes lambda as type 'ante-bytes' messages.
> Subscribe impressions to the ddb kinesis stream

- ci/ci.yml
- dns/prxu.org-hosted_zone.yml
- etc/wildcard-certificate.yml
- stacks/certificate.yml
The `prxu.org` DNS change has already been deployed.
The stack certificate change deploy should be watched somewhat closely. I have made sure that all the validation records it requires to mint the new certificate already exist, so it should deploy without intervention, but in case I missed something we'd want to create those records while it's deploying to prevent a rollback.
> DNS stack cert validation

- cdn/dovetail-cdn.yml
For PRX/internal#518.
We've been running "unofficial" dovetail CDN alarms for awhile - since our rate mysteriously increased in December.  This PR updates them, and makes them more permissive of our overnight error rate (which appears to go up, as there's less overall traffic but the same-ish number of 5XXs?).
> CDN 5XX rate alarms

- stacks/serverless/dovetail-traffic-lambda.yml
- stacks/serverless/root.yml
After PRX/dovetail-traffic-lambda#5.  Init a kinesis trigger on `dovetail-metrics-6s`.
Also should check that we have plenty of space for another stream consumer.
> Kinesis traffic trigger

- ci/ci.yml
V1 doesn't look to be supported any more, and is missing new runtimes, like node 12
> Update CI Docker image version

- stacks/dovetail.prx.org.yml
> Dovetail Router basic alarms

- stacks/ecs.yml
- utility/lambdas/ecs-asg-sizer/lambda_function.py
The ASG sizer lambda has been killing EC2 instances with disconnected ecs-agents a bit too frequently.  Turns out, sometimes the ECS `agentConnected` may briefly report `false` even though the instance is fine.
This encodes in a tag the epoch seconds when an EC2 instance is seen with an ECS agent disconnected.  Then the instance must remain disconnected for 5 minutes for to get manually terminated.
> Track how long ECS agents have been disconnected

- stacks/serverless/analytics-ingest-alarms.yml
- stacks/serverless/analytics-ingest-lambdas.yml
> Analytics ddb alarms

- stacks/vpc.yml
This could alter which AZs our subnets are in. In particular, it will likely no longer skip `us-east-1b`, since they changed how the letters map to actual AZs, so all accounts are now guaranteed to have sequential AZs available.
> Modernize VPC subnets

- stacks/vpc.yml
This should revert the VPC subnet CIDR blocks and AZs to the *exact* values that they've been for the last few years.
It also adds an `UpdateReplacePolicy` set to `Retain` for the subnet resources. This only comes into play when a stack update needs to replace a resource (ie, create a new one and delete the old one after dependencies have been switched over), which is the case for changing the AZ or CIDR on a subnet. With the resources set to `Retain`, CloudFormation will do all it's normal things, but leave the old subnets around rather than delete them. It *won't* keep them as stack resources – it doesn't delete them but it does forget about them (also what we want).
[Here's](https://github.com/PRX/Infrastructure/compare/d3c94b8e12649a8de03ce3e60398b26bf973065f..5a9d7c1c788960838dd047aa3 …
> Unmodernize subnets

- dns/prx.org-hosted_zone.yml
Continues the work on https://github.com/PRX/internal/issues/520
> Remove legacy WordPress DNS records

- stacks/certificate.yml
To make it more obvious that the certificate is legitimate
> Use prx.org as certificate common name

- cdn/single-origin.yml
Replaces some deprecated properties (DefaultTTL, MaxTTL, MinTTL, ForwardedValued) with new CachePolicy and OriginRequestPolicy resources.
This allows for more granular control over differences between caching behavior and origin request behavior. It also allows support for newer features, like Brotli compression.
Builds will fail until cfn-lint catches up on Brotli support.
> Replace deprecated cache properties in single-origin template

- ci/lambdas/ci-status-notification-handler/index.js
- ci/lambdas/codebuild-callback-handler/lambda_function.py
- ci/lambdas/github-event-handler/index.js
- stacks/container-apps/sphinx-nlb.yml
Currently in a build notification the repo name (e.g., "PRX/Porter") is hyperlinked to CodeBuild. This changes that to the word "build" or "building" to be more obvious
Closes #434
> Make CI Slack notifications more intuitive

- ci/lambdas/ci-status-notification-handler/index.js
- ci/lambdas/codebuild-callback-handler/lambda_function.py
- ci/lambdas/github-event-handler/index.js
- ci/lambdas/github-webhook-endpoint/index.js
- ci/utility/post_build.sh
- package.json
- stacks/container-apps/sphinx-nlb.yml
- tsconfig.json
In preparation for [the upcoming changes](https://github.com/github/renaming/) to default branch naming, this will allow the CI system to build properly for any default branch name, not just `master`.
This PR also modernizes the Lambda code for several steps in the CI process. Key changes are: replacing some callbacks and `then` calls with asycn/await; adding type hinting; replacing several uses of a deprecated url method.
> Modernize CI Lambdas

- db/mysql-instance.yml
- db/postgresql-instance.yml
There was a smattering of use of both DeletionProtection to prevent deletes and DeletionPolicy(on psql, but not mysql).
Also add to both the UpdateReplacePolicy to retain resources on update/replace Cfn executions.
(Which, fwiw, also satisfies the cfn-lint warning)
> Update deletion and update retention policies to retain resources

- storage/storage.yml
- Adds UpdateReplacePolicy for all bucket resources
- Replaces a `join` to build the bucket URL with a more direct return value, which didn't exist when the template was first made. (This does change the URL from a path-style URL to virtual host. I don't think this value is actually being used anywhere, but it shouldn't matter even if it is)
- Small syntax changes
> Modernize storage template

- stacks/serverless/pixel.prx.org.yml
Adds an unused HTTP API version of the Pixel API alongside the REST API, to do some initial testing.
This is to start the process of moving to faster/cheaper HTTP APIs in cases where we don't rely on any REST-only functionality.
> Add HTTP API and SAM function for Pixel tracker

- stacks/dovetail.prx.org.yml
- stacks/root.yml
If Dovetail (nodejs) logs info messages with `{"msg": "impression"}` or `{"msg": "impressionbytes"}` - send those to kinesis.
> Send dovetail logged impressions to kinesis streams

- cdn/single-origin.yml
This is a backwards-compatible update to the template that allows for an optional failover domain to be passed in as a parameter. When that parameter is present, an additional origin is created, both origins are placed into an _origin group_, and the origin group is set as the target for the default cache behavior. When the parameter is omitted, the template behaves as it did prior to this change.
The failover configuration supports any of the following status codes acting as failover triggers: 403, 404, 500, 502, 503, 504. Currently the template offers three sets of values. Any other combination of codes can be added should the need arise.
> Add support for a failover origin to the single origin template

- stacks/publish.prx.org.yml
Creates a new bucket to be used (in the future) for Publish uploads temp storage. For now it just passes the environment variables in in a way that matches how they will work with the new bucket.
> Publish S3 bucket refactor

- stacks/publish.prx.org.yml
Closes #471
Flips the switch on using the new template-provided S3 bucket for Uploads, as well as a CloudFront distribution in front of the bucket to provide the necessary public access to the uploads
> Use inline Publish bucket and CDN in production

- db/dynamodb-table.yml
I've already deployed these changes to the Dovetail "arrangements" tables in the data accounts.
I'm using pay-per-request tables with 0 alarms there, until we get a bit closer to this being live.  Then will add some alarms, and maybe flip prod to the cheaper provisioned eventually.
> Per-request DDB table fixes

- stacks/dovetail.prx.org.yml
Closes PRX/dovetail-router.prx.org#106
Add a `TargetTrackingScaling` autoscaling policy to dovetail-router.
I set the initial target to 1000 requests per target, per 1 minute:
- Prod was previously averaging ~40 requests per-target-per-minute and ~15ms response times.
- Prod is now averaging 180 requests per-target-per-minute, and ~19ms response times.
- Load testing staging, it seem like we could do at least 1000 per target.  At ~5K requests per target, response times degraded to more like 75ms, but things still seemed stable / error-free.
Current Dovetail (nodejs) does something like ~8000 requests per minute, amongst ~20 targets - so more like 400 per target.  And averages ~70ms per request.  So I think we'll at least be able to cut our tasks in half with better response times.
> Dovetail-Router autoscaling

- stacks/container-apps/augury-forecast.yml
To deploy with PRX/augury.prx.org#465
> Throttle augury forecasts

- stacks/container-apps/cms.prx.org.yml
- stacks/container-apps/root.yml
Moves CMS into its own template, rather than using the shared web-app template (necessary for IAM role changes as well).
Creates the CMS memcached cluster along side the other CMS app resources. Currently the cluster is created, but dormant, in production.
> Create CMS memcached in CMS stack

- stacks/shared-memcached.yml
Per [the docs](https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/CacheMetrics.WhichShouldIMonitor.html#metrics-swap-usage) on `SwapUsage` ...
> This metric should not exceed 50 MB. If it does, we recommend that you increase the ConnectionOverhead parameter value.
We don't have a ton of CloudWatch historical data on memcached, but i do see that metric tends to garbage-collect and drop suddenly.  And since we won't take any action until this alarm hits 50 ... changed the "warn" to 32, and "error" to 50.
> Memcached SwapUsage alarms

- storage/multi-region-replication/ad-files.yml
Per https://github.com/PRX/augury.prx.org/issues/545
This sets up some CORS rules for the ad files upload buckets. Opaque uploads alread work via xhr + signed requests, this just allows some response data to come back to the uploader javascript thread.
> Set up cors on ad-upload buckets

- stacks/serverless/analytics-ingest-filters.yml
- stacks/serverless/analytics-ingest-lambdas.yml
Now that the `analytics-dynamodb-lambda` output is a CloudWatch Log Subscription, it's much more dense (a bunch of gzipped log lines into single kinesis records).
Consequently, we need to decrease batch sizes and increase memory to deal with the increased downloads/impressions-per-batch.
> Analytics lambdas tune-up

- stacks/ecs.yml
- stacks/root.yml
- stacks/shared-ecs-asg.yml
Only enabled in the new, staging-only ASG for testing.
> Add Redis connectivity check to ASG cfn-init

- stacks/serverless/dovetail-counts-lambda.yml
- stacks/serverless/root.yml
Deploy before PRX/dovetail-counts-lambda#37.
> Allow counts-lambda to read from DDB

- stacks/apps/augury.yml
- stacks/container-apps/augury-alarms.yml
Merge this after https://github.com/PRX/augury.prx.org/pull/579 lands
This PR consolidates the metrics, reflecting the single invocation of the partitions forecast R script.
> Consolidate the metrics due to Augury Agent forecast changes

- stacks/apps/augury.yml
- stacks/container-apps/augury-alarms.yml
Took another pass related to https://github.com/PRX/augury.prx.org/issues/527 on clearing up collisions in the metrics / filters namespaces.
> Make sure alarm/metrics namespaces don't collide

- db/postgresql-instance.yml
Per https://github.com/PRX/augury.prx.org/issues/577
This turns on cloudwatch logging for the shared postgres database
[The docs indicate ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-enablecloudwatchlogsexports)that this is not going to interrupt the database.
> Turn on cloudwatch logging for shared PG instance

- storage/multi-region-replication/feeds.yml
- storage/multi-region-replication/mediajoint.yml
- storage/multi-region-replication/networks.yml
The mediajoint, networks, and feeds buckets previously did not have versioning enabled. In order to support replication, version had to be enabled. This will create a lifecycle rule that expires (i.e., permanently deletes) non-current versions of all objects in the bucket, which will prevent any unnecessary buildup of old object versions.
> Permanently delete non-current object versions

- stacks/apps/augury.yml
- stacks/apps/cms.yml
- stacks/apps/exchange.yml
- stacks/apps/feeder.yml
- stacks/apps/id.yml
- stacks/apps/networks.yml
- stacks/apps/remix.yml
- stacks/container-apps/augury-forecast.yml
- stacks/container-apps/augury.prx.org.yml
- stacks/container-apps/cms.prx.org.yml
- stacks/container-apps/exchange.prx.org.yml
- stacks/container-apps/feeder.prx.org.yml
- stacks/container-apps/id.prx.org.yml
- stacks/container-apps/iframely.prx.org.yml
- stacks/container-apps/networks.prx.org.yml
- stacks/container-apps/remix.yml
- stacks/container-apps/sphinx-nlb.yml
Consistently use stack params for setting the db hosts/ports, instead of AWS secrets.  Note that prod is still pointed at non-Aurora at this point.
Deploying this:
> Use stack params for db host/port

- stacks/apps-200A.yml
- stacks/apps/feeder.yml
- stacks/container-apps/feeder.prx.org.yml
- stacks/root.yml
🚧  DO NOT MERGE until ready to move the DB.
Use Aurora for all Feeder DBs, all the time.
> Feeder to Aurora

- stacks/apps/cms.yml
- stacks/apps/feeder.yml
- stacks/container-apps/cms.prx.org.yml
- stacks/container-apps/feeder.prx.org.yml
- stacks/shared-announce.yml
> Fixup queue names

- stacks/apps/augury.yml
These aren't inherited from the task definition, apparently
> Add tags to Fargate task runs

- stacks/apps/cms.yml
- stacks/apps/feeder.yml
These should be much closer to the least privilege requirements of both apps. Hopefully not removing any necessary permissions?
> Cleanup Feeder and CMS SNS and SQS policies

- stacks/apps/augury.yml
Looks like fargate memory usage is peaking at around 10gigs, so lower the bound on memory usage
.
> Lower augury fargate memory

- stacks/apps/augury.yml
Sets up a new alarm to make sure the forecasts are running, uses the forecasts metrics filter.
> Set up an alarm for missing forecasts

- stacks/apps/augury.yml
Expands the sampling interval to three 15 minute periods.
I forgot there was a 30 minute 'buffer' in the schedule at the [end of the day](https://github.com/PRX/augury.prx.org/blob/ed1c30e496dae6106f847973b234faa2ef374759/app/jobs/schedule_forecasts_cron_job.rb#L20), so that the forecasts don't run over the next day's forecasts.
> Bump to 3 periods of 15 minutes

- stacks/shared-ecs/asg.yml
Bring back the [ECS task draining](https://github.com/PRX/Infrastructure/blob/bcdbefed9ad2cddf5bc8d1112b254918789e06c1/stacks/ecs.yml#L653) lambda/SQS.  Attempts to convert to `AWS::Serverless::Function` - we'll see if that works!
Just staging for now.
> ECS draining

- stacks/apps-100A.yml
- stacks/apps-300A.yml
- stacks/apps/dovetail-analytics.yml
- stacks/apps/dovetail-counts.yml
- stacks/apps/dovetail-router.yml
- stacks/apps/dovetail-traffic.yml
- stacks/root.yml
- stacks/shared-dovetail-kinesis.yml
- stacks/shared-kinesis.yml
Merge carefully!
We've been using 3 kinesis streams not in CFN:
- `dovetail-bytes-production` the output of CloudFront; input to dovetail-counts
- `dovetail-ddb-production` the output of both DTR logs and dovetail-counts; input to analytics-dynamodb
- `dovetail-metrics-production-6s` the output of analytics-dynamodb, input to analytics-bigquery/redis/pingbacks
Move these into CFN, so we can deploy them in another region!  This keeps the old streams as deprecated-triggers for now, until they empty.  And we update CloudFront.
> Analytics kinesis streams

- stacks/apps/dovetail-analytics.yml
Starting to move the analytics DDB from the data accounts into this stack.  Reasoning being: this "temporary cache of DTR redirect data" should be tied to a specific region/Dovetail-stack.
So this PR:
- Creates a new table directly in the `dovetail-analytics.yml` stack
- Sets up capacity scaling (hopefully) the same way as the data accounts
- Adds a temporary redundant `analytics-dynamodb-lambda` function, hooked up to the same kinesis stream as the real thing.
- New lambda will insert (hopefully) the same data into the new table.  But has no output subscription-filter.
- In > 24 hours (hopefully) our tables will reach parity.  And we can point the real function at the new table, and delete this temporary function.
> New analytics DDB table

- cdn/dovetail-cdn.yml
- dns/prxu.org-hosted_zone.yml
- Adds optional secondary and tertiary regions (behaviors) to the dovetail-cdn stack.
- You can configure those behaviors to log to different kinesis streams
Not exactly a no-op, as it cycles some of the live-log configs.  So expect a bit of a blip in metrics - definitely deploy after hours.  But will initially deploy with just the us-east-1 region set (probably prefix `use1` or something).
But should allow processing analytics in a 2nd or 3rd region.
> Multi-behavior dovetail cdn

- stacks/apps/dovetail-router.yml
- stacks/jump-server.yml
- stacks/root.yml
Adds some regional DNS entries for the jump servers and dovetail-router:
```
jump.us-east-1.prx.tech
jump.staging.us-east-1.prx.tech
dovetail-router.us-east-1.prx.tech
dovetail-router.staging.us-east-1.prx.tech
```
Also makes the castle dependency on the jump servers optional.
> Jump server in every region

- stacks/jump-server.yml
- stacks/root.yml
Add some envs to un-hardcode things in the `awssh` and `awstunnel` scripting.  Given a region and environment-type, they should be able to ssh you into the jump server and pull the configs you need.
I'd also like to get all `awssh` traffic going _through_ the jump server instead of having port 22 open on every ECS instance.  Someday...
> Add some ENVs to jump servers

- stacks/apps-300A.yml
- stacks/apps/augury.yml
- stacks/apps/dovetail-analytics.yml
- stacks/root.yml
- stacks/shared-vpc/interface-endpoints.yml
Adds a VPC Endpoint for SSM.
Also gives the shared ECS security group access to the endpoint.
Also gives explicit access to Augury slow worker and Dovetail Analytics Redis
> Create SSM VPC Endpoint

- stacks/apps/exchange.yml
- stacks/root.yml
- Updates shared hostname value to new domain, which is used in `COUNT_HOST` envar
- Removes `COUNT_HOST_NEW` envar
> Use only new hostname for The Count

- dns/prx.org-hosted_zone.yml
- stacks/apps/the-count.yml
- Removes legacy `count.prx.org` Contegix DNS record
- Replaces hard-coded `thecount.prx.org` value with the hostname parameter, which is now also `thecount.prx.org`
> Clean up DNS for The Count

- stacks/apps/exchange.yml
On top of the per series use_porter flag, this switches all deliveries to Porter, even those not in a series, or in a series not flagged to use Porter.
> Switch all deliveries to go to Porter

- stacks/apps-300A.yml
- stacks/apps/dovetail-router.yml
Leaving us-east-1 without a `REDIRECT_PREFIX` for now.  CloudFront knows that us-east-1 is the "default" region to send a realtime log to, when a request has no `/use1/` or `/usw2/` prefix/behavior.
> Add redirect prefix to non-primary regions

- dns/theworld.org-hosted-zone.yml
gsuite.theworld.org pointed to PRX Gmail
(done correct this time)
> gsuite subdomain for The World email migration

- dns/theworld.org-hosted-zone.yml
added two lines - MX record for o365.theworld.org pointing at GBH, and an MS verification TXT for theworld.org
Once you approve this one, go ahead and push it live, thanks!
> Office 365 side email migration changes

- stacks/apps-100A.yml
- stacks/apps/id.yml
For PRX/id.prx.org#276.
- Adds a new S3 bucket, for ID temporary image uploads
- Configure for Porter image processing/callbacks
- Remove CMS references (already gone from ID codebase)
> Image uploads

- stacks/apps/dovetail-router.yml
- stacks/apps/dovetail-traffic.yml
Upcoming changes will cut off the traffic lambda from generating fake downloads on our staging/demo podcasts.
This wires up a shared secret to continue allowing it for our demo/test podcasts.
> Dovetail traffic lambda secret

- stacks/apps/feeder.yml
- part of the feeder rails 7 upgrade PR https://github.com/PRX/feeder.prx.org/pull/469
- adds now standard naming for postgres env var connection info
- once deployed, the old variable names `DB_ENV_*` can be removed
> Change to standard postgres env var names, like augury

- etc/cdn-log-shipper/log-shipper.yml
Per some IAB2.1...
We should only use half of IPv6 when calculating listener_ids.  But continue using all of IPv4.
While I was at it - also truncated the shipped IPv6 IPs / XFFs the same way.
Should probably test this out carefully before actually deploying.
> Truncate shipped IPv6s

- stacks/apps-100A.yml
- stacks/apps/dovetail-apple-api-bridge.yml
- stacks/dashboards.yml
- stacks/root.yml
Looking at the upload functionality in feeder, I noticed that the http api gateway trigger has a fixed timeout and does not reflect the underlying lambda's timeout.
Digging a bit deeper, it looks like the lambda url resource on the lambda itself can be used to invoke the lambda directly and will honor the underlying timeout.
This PR:
- sets up a new lambda url resource on the lambda
- removes the api gateway trigger
- patches that new url through the stacks in place of the api gateway url
> Drop http api in favor of lambda url

- stacks/apps/feeder.yml
I also sorted the ENVs, so probably easiest to review commit by commit.
Summary of changes:
- Removed `APP_NAME` ... that was an aws-secrets thing
- Removed `APP_ENV` ... also an aws-secrets thing
- Removed `DB_PORT_` vars - they were deprecated awhile back
- Removed `FIXER_CALLBACK_QUEUE_NAME` - Feeder doesn't use it.  It actually [interpolates it](https://github.com/PRX/feeder.prx.org/blob/main/app/models/task.rb#L58).
- Removed `LANG` - rails defaults to `en_US.UTF-8` anyways
- Removed `RAILS_SERVE_STATIC_FILES` - Feeder always serves static files now
- Removed `WORKER_PAUSE` - it already [defaults to 30](https://github.com/PRX/feeder.prx.org/blob/master/config/shoryuken.yml#L7)
- Removed `OTEL_` honeycomb stuff - unused.
- Removed `WORKER_DATABASE_POOL_SIZE`, and just set …
> Cleanup Feeder ENVs

- stacks/apps/exchange.yml
I don't know if this is why Exchange stopped reporting to NR, but it's the only app that didn't have this name configured as an envar. Maybe that's required now? I doubt it, but seems good to have here anyway.
> Add NEW_RELIC_NAME to Exchange envars

- stacks/apps/augury.yml
Augury webs should be as spread out as possible.  Ideally only 1 per EC2 instance.
> Spread out augury web tasks

- stacks/apps/feeder.yml
Sets up a new `feeder_publishing`  queue for feeder jobs to work on publishing artifacts (RSS/Apple/etc).
Copies the default queue baseline CFN params for the SQS resource.
> Add a new publishing queue for the feeder app

- stacks/apps/dovetail-cdn-arranger.yml
- stacks/apps/dovetail-counts.yml
- stacks/apps/dovetail-traffic.yml
Could find anything that looked problematic in the app
https://github.com/PRX/dovetail-traffic-lambda
> Use Node.js 16 for Dovetail Lambdas

- etc/cdn-log-shipper/log-shipper.yml
For #684 
Not totally sure how to test this, but using a local script this seems to work ~, adding a single column for `byte-range`~
actually, they are fine with the separate start and end columns, they did ask for a hashed ip, so adding that instead.
*Don't merge until we get confirmation they want the truncated ipv6 used for the hashed ip*
> Add hashed ip for Triton

- stacks/apps-200A.yml
- stacks/apps/feeder.yml
Sets up alarms that are triggered on error log levels, similar to Augury.  A way to send messages to the team about errors, without relying on exceptions bubbling up, for things like https://github.com/PRX/feeder.prx.org/issues/714
> Set up feeder alarms on error log levels

- stacks/apps/feeder.yml
Need to also replace the auth in the RSS atom link:
```xml
<atom:link href="https://p.prxu.org/4647/subscriber/feed-rss.xml{?auth}" rel="self" type="application/rss+xml"/>
```
This auth proxy code feels kind of brittle?  But since we (Feeder) controls the RSS generation, I think this is pretty safe for now.  Until we want to rewrite this lambda as something better than an API Gateway (which has some known file size limitations) - that feels like the time to improve this code.
> Fix feeder auth proxy atom link

- spire/templates/apps-200A.yml
- spire/templates/apps/feeder.yml
- spire/templates/constants.yml
- spire/templates/root.yml
Adds the `PUBLIC_FEEDS_URL_PREFIX` env to the feeder stack.
> Publicfeeds.net

- spire/templates/apps/dovetail-router.yml
- storage/multi-region-replication/feeds.yml
Closes #698
- Updates S3 bucket config (already deployed)
- Removes the bucket name from the EventBridge rule for triggering the scaler Lambda. This will now match on `Object Created` from any bucket, but we have EventBridge notifications turned on for very few buckets, and the likelihood of objects with these names being created in another bucket are pretty low. And even if we do get those false positives, we just scale up unnecessarily for a bit, which isn't really a problem.
> Router scaling

- spire/templates/apps-300A.yml
- spire/templates/apps/augury.yml
- spire/templates/apps/feeder.yml
- spire/templates/constants.yml
- Change `augury.` to a redirect
- Unify staging and prod rules for Feeder
- Send `/api` and `/api/*` Feeder traffic directly to target group
- Redirect all other traffic to `feeder.` to `podcasts.dovetail`
> Update hostnames for Augury and Feeder

- spire/templates/apps/augury.yml
Try switching from round-robin to least_outstanding requests to alleviate pressure on tasks with running requests.
> Switch from round_robin to least_outstanding_requests

- spire/templates/apps/feeder.yml
Do this or https://github.com/PRX/feeder.prx.org/pull/918
> Allow feeder to delete S3 objects

- storage/multi-region-replication/ftp-transfer.yml
activated manually for the bucket via the console
> Enable replication time control for the prxtransfer prod s3 bucket

- cdn/dovetail-cdn/cloudfront.yml
This shouldn't have any real impact for us, but 2.0 does include some newer JavaScript features we may want to use in the future.
> Use CloudFront Function JavaScript runtime 2.0 for Dovetail CDN

- cdn/publicfeeds-cdn.yml
Makes a HEAD request to the same file as the origin request, looks for a `x-amz-meta-dovetail-feed-cdn-redirect` header, if present returns a 301 to that header's value.
- Example without metadata set on S3 object: [`https://staging.publicfeeds.net/f/100/feed-rss.xml`](https://staging.publicfeeds.net/f/100/feed-rss.xml)
- Example with metadata set (`https://example.com`) on object: [`https://staging.publicfeeds.net/f/101/feed-rss.xml`](https://staging.publicfeeds.net/f/101/feed-rss.xml)
Closes https://github.com/PRX/internal/issues/1086
> Handle redirect headers on S3 feed objects

- spire/templates/apps/dovetail-cdn-arranger.yml
- spire/templates/root.yml
- spire/templates/shared-dovetail-kinesis.yml
This is a more modern method of granting access to resources based on organization membership.
Rather than comparing the organization ID of the principal making a request to a static value, it compares the policy's own organization ID (represented by `aws:ResourceOrgID`) to a dynamic value coming from the policy evaluation (`${aws:PrincipalOrgID}`). When they're the same, the resource associated with the policy and the requesting principal are in the same organization, so access should be granted.
This achieves the same thing without having to pass the organization ID around every time this pattern is used.
> Use policy variable for organization access

- spire/templates/shared-vpc/flow-logs.yml
To support [the newest](https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-vpc-flow-logs-for-elastic-container-services/) version of flow log format that include ECS data, I think we need to create a new flow log.
This replaces the existing flow log with a new one by changing the resource name, and also update some of the resource definition to the more modern format.
> Force FlowLog resource replacement

- dns/theworld.org-hosted-zone.yml
Update DNS to add records needed to get The World podcast feeds off Feedburner, and get YML file in sync with DNS changes made via Route 53 admin.
> __DO NOT MERGE/DEPLOY UNTIL ROUTTE 53 HAS BEEN UPDATE TO REVERT CHANGES TO MATCH YML DEFINITIONS PRIOR TO THIS PR.__
New feed records (provided via [Google doc](https://docs.google.com/spreadsheets/d/1BOCZlwOfa0RxGFf8pVwHLeyjxdvuVM57CFmDLgWzTw4/edit?gid=0#gid=0))
- add latest-edition.feed acm validation record
- add latest-edition.feed publicfeeds CNAME record
- add latest-stories.feed acm validation record
- add latest-stories.feed publicfeeds CNAME record
The following changes were made to get YML in sync with Route 53 (records changes tracked [here](https://prx.slack.com/lists/T0256R4CK/F07GT1P2203)):
- update admin records to point to WP …
> Update theworld.org DNS

- spire/templates/apps/castle.yml
- spire/templates/apps/cms.yml
- spire/templates/apps/dovetail-analytics.yml
- spire/templates/apps/dovetail-counts.yml
- spire/templates/apps/exchange.yml
- spire/templates/apps/feeder.yml
- spire/templates/apps/s3-signing.yml
- spire/templates/shared-memcached.yml
Closes https://github.com/PRX/internal/issues/1131
To be seen how often these don't have data. I'm assuming only during fairly major AWS issues. But we can dial things back if it's noisy. I went with `missing` rather than `breaching` so at least make it obvious when we see alarms because of this change.
> Treat missing data for some alarms as missing

- package.json
- spire/templates/apps/dovetail-router.yml
- yarn.lock
This probably needs at least one real-world test run. Some of the v3 SDK commands work a little differently than v2. I think I accounted for all of them, but worth checking.
Closes #733
> Upgrade Router scaler function to Node.js 20 and AWS SDK v3

- spire/templates/apps/castle.yml
`13.13` is the version already being used by both stag and prod Castle DBs, the template seems to have gotten out of sync
> Update Castle DB version

- spire/templates/apps/dovetail-cdn-arranger.yml
Hit an issue where a flac transcode needed more than 512mb.
> More cdn-arranger tmp storage

- spire/templates/apps/dovetail-marketing-form-handler.yml
goes with https://github.com/PRX/dovetail-marketing-site/pull/34
> Update the form for ip optout

- spire/templates/root.yml
- spire/templates/shared-redis/cluster.yml
We've hit some high memory alarms in us-west-2.  Revert to cache.m6g.large for now.
> Use cache.m6g.large everywhere

- spire/templates/apps/augury.yml
- spire/templates/apps/castle.yml
- spire/templates/apps/cms.yml
- spire/templates/apps/dovetail-router.yml
- spire/templates/apps/exchange.yml
- spire/templates/apps/feeder.yml
- spire/templates/apps/id.yml
- spire/templates/apps/iframely.yml
- spire/templates/apps/metrics.yml
- spire/templates/apps/networks.yml
- spire/templates/apps/play.yml
- spire/templates/apps/remix.yml
- spire/templates/apps/styleguide.yml
- spire/templates/apps/the-castle.yml
- spire/templates/apps/theworld-website.yml
- spire/templates/apps/wfmt.yml
This adds `PlacementConstraints` to each existing ECS service, ensuring that associated tasks are only placed on `x86_64` instances.
This shouldn't make any functional change to existing deployments, since all instances are `x86_64`.
> Add instance-type placement constraint to ECS tasks

- spire/templates/shared-alb.yml
Adds a WAF to the shared ALB. Does not change the Dovetail Router ALB.
Meant to mimic the setup/rule that we currently have deployed.
This shouldn't be deployed until the existing WAF is torn down.
> Shared ALB WAF

- spire/templates/apps-100A.yml
- spire/templates/apps-200A.yml
- spire/templates/apps-300A.yml
- spire/templates/apps-400A.yml
- spire/templates/apps/augury.yml
- spire/templates/apps/castle.yml
- spire/templates/apps/cms.yml
- spire/templates/apps/dovetail-insights.yml
- spire/templates/apps/dovetail-router.yml
- spire/templates/apps/exchange.yml
- spire/templates/apps/feeder.yml
- spire/templates/apps/id.yml
- spire/templates/apps/iframely.yml
- spire/templates/apps/metrics.yml
- spire/templates/apps/networks.yml
- spire/templates/apps/play.yml
- spire/templates/apps/remix.yml
- spire/templates/apps/styleguide.yml
- spire/templates/apps/the-castle.yml
- spire/templates/apps/theworld-website.yml
- spire/templates/apps/wfmt.yml
- spire/templates/root.yml
- spire/templates/shared-ecs/asg-aarch64.yml
- spire/templates/shared-ecs/asg-x86-64.yml
- Reverts the default capacity provider strategy for the ECS cluster to use only the x86 capacity provider (this only affects ECS services (not tasks) that are created from this point forward, it's essentially a no-op)
- Intended to explicitly set the capacity provider strategy on every ECS service and non-service task (things that use `runTask`, like cron workers and Augury slow worker Lambda function).
If this PR misses any services/tasks, that's not really a big deal (at this point), since they will continue to work as they have been.
The bigger deal would be if this gets the provider strategy _wrong_ (aarch64 when it should be x86, a malformed definition, etc) for any of the resources that it is affecting. This is redefining the capacity strategy for all ECS services, some which …
> Service capacity providers

- spire/templates/shared-app-redis.yml
- spire/templates/shared-redis/cluster.yml
Should essentially be recreating [what we had](https://github.com/PRX/Infrastructure/blob/f7dd8140a90f328c9c47e301e98857cd1f1cb341/spire/templates/shared-app-redis.yml#L77), but using `AWS::ElastiCache::ReplicationGroup` instead of `AWS::ElastiCache::CacheCluster`, which doesn't support valkey.
> Use hosted Valkey for apps, switching to ReplicationGroup

- spire/templates/apps/castle.yml
- Make the DB instance conditional, which should tear down the existing instance in us-west-2
- Returns bogus placeholder values for address, port, and instance ID when the instance doesn't exist
The two things that currently depend on those values are:
- Augury task definitions use them as environment variables. Since we don't run Augury tasks in secondary regions, the bogus values should never cause a problem
- Jump servers also use them as envars (`export PRX_CASTLE_POSTGRES_HOST=${CastlePostgresInstanceEndpointAddress}`). I think the bogus values would only cause a problem if someone tried to connect to the Castle DB in a region that we don't use, so I'm not worried about that. There is probably a cleaner way to handle that, and exclude those values from the jump server ENV entirely …
> Remove Castle DB instance in secondary regions

- spire/templates/apps/feeder.yml
Saw a couple requests this morning that exceeded the 192mb memory this lambda had.  No idea which, as we don't log that.
Bumping the memory a bit and logging the feed urls for future debugging.
> Auth Proxy fixes

- spire/templates/apps/feeder.yml
The worker for Megaphone imports "simulates" uploading the audio to the uploads bucket, so the task needs access to wrote to this bucket.
> Give feeder tasks access to the uploads bucket

- spire/templates/apps-100A.yml
- spire/templates/apps-200A.yml
- spire/templates/apps-300A.yml
- spire/templates/apps/castle.yml
- spire/templates/apps/dovetail-counts.yml
- spire/templates/apps/dovetail-router.yml
- spire/templates/jump-server.yml
- spire/templates/root.yml
Moving dovetail to a new valkey cluster.
This PR just clones writes in staging, for DTR and the counts-lambda.  Castle just uses redis more like a traditional cache these days, but moving that to the new valkey as well.
> Dovetail to valkey

- etc/pgdump-to-s3/template.yml
Moves the scheduled time to run pg_dump from 00:15am UTC to 04:30am UTC.
We have some other transaction heavy workloads for augury that this can work around:
- 00:00 UTC midnight reallocation
- 08:00am Collection flight resmoothing
And in general this pushes the pg_dump invocation further away from regular office hours.
> Reschedule pg-dump cron
